// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRL2OwINkshaKrSgz0uRZmk27jQBXN1zk',
    appId: '1:639834711389:web:67b024e2b8c4cda2f134b4',
    messagingSenderId: '639834711389',
    projectId: 'redditapp-a217e',
    authDomain: 'redditapp-a217e.firebaseapp.com',
    storageBucket: 'redditapp-a217e.appspot.com',
    measurementId: 'G-WMXYZLG3EH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6DrDAlY3-dP9KOnYbSxEQDWSG4oGMGB4',
    appId: '1:1018113911970:android:18a3b7b9233c06054f7bfb',
    messagingSenderId: '1018113911970',
    projectId: 'redditapp-baebd',
    storageBucket: 'redditapp-baebd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtsdo0JMJFexE2l50k4_sK0LiKTOLotng',
    appId: '1:1018113911970:ios:63220b522a8e20e74f7bfb',
    messagingSenderId: '1018113911970',
    projectId: 'redditapp-baebd',
    storageBucket: 'redditapp-baebd.appspot.com',
    iosClientId: '1018113911970-0m27v49ohrbepn2bunqg48pv4tec6tvf.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB82itwCHXkotuA6eUieCItl85_ta32nhk',
    appId: '1:639834711389:ios:2e18d5c9c9589742f134b4',
    messagingSenderId: '639834711389',
    projectId: 'redditapp-a217e',
    storageBucket: 'redditapp-a217e.appspot.com',
    iosBundleId: 'com.example.redditApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcwA0E0DCwjQaynidUX3pbqFR2DArlhPs',
    appId: '1:1018113911970:web:7c3c6efe44ab14574f7bfb',
    messagingSenderId: '1018113911970',
    projectId: 'redditapp-baebd',
    authDomain: 'redditapp-baebd.firebaseapp.com',
    storageBucket: 'redditapp-baebd.appspot.com',
    measurementId: 'G-N4KPZKP9BE',
  );

}